---
docker:
  builds:
    - path: .
      dockerfile: Dockerfile
      docker_repo: resin/open-balena-registry

    - path: .
      dockerfile: Dockerfile
      docker_repo: balena/open-balena-registry
