[template]
src = "docker-registry.yml.tmpl"
dest = "/etc/docker-registry.yml"
keys = [
  "COMMON_REGION",
  "REGISTRY2_CACHE_ADDR",
  "REGISTRY2_CACHE_DB",
  "REGISTRY2_CACHE_ENABLED",
  "REGISTRY2_DISABLE_REDIRECT",
  "REGISTRY2_HOST",
  "REGISTRY2_PROXY_ENABLED",
  "REGISTRY2_PROXY_PASSWORD",
  "REGISTRY2_PROXY_REMOTE_URL",
  "REGISTRY2_PROXY_USERNAME",
  "REGISTRY2_S3_BUCKET",
  "REGISTRY2_S3_CLOUDFRONT_ENDPOINT",
  "REGISTRY2_S3_CLOUDFRONT_KEYPAIR_ID",
  "REGISTRY2_S3_KEY",
  "REGISTRY2_S3_REGION_ENDPOINT",
  "REGISTRY2_S3_SECRET",
  "REGISTRY2_SECRETKEY",
  "REGISTRY2_STORAGEPATH",
  "REGISTRY2_TOKEN_AUTH_ISSUER",
  "REGISTRY2_TOKEN_AUTH_REALM"
]
