[template]
src = "config.tmpl"
dest = "/config/config.yml"
keys = [
  "/services/registry_s3_bucket",
  "/services/registry_s3_access_key",
  "/services/registry_s3_secret_key",
  "/services/registry_storage_path",
  "/services/registry_secret_key"
]
