[template]
src = "docker-registry.yml.tmpl"
dest = "/etc/docker-registry.yml"
keys = [
  "COMMON_REGION",
  "REGISTRY2_SECRETKEY",
  "BALENA_REGISTRY2_HOST",
  "BALENA_TOKEN_AUTH_REALM",
  "BALENA_TOKEN_AUTH_ISSUER",
  "REGISTRY2_S3_BUCKET",
  "REGISTRY2_S3_KEY",
  "REGISTRY2_S3_SECRET",
  "REGISTRY2_STORAGEPATH",
]
